### ISSUE TITLE
script commands return null

### ISSUE THREAD

**Issue by luispb** [thorsten-gehrig/alexa-remote-control#100]
I'm not sure what I'm doing wrong. If I do 'alexa_remote_control.sh -a' I get a list of all the devices in my account. 
The problem is that I'm not able to send any command to any of them. All return 'null'
For example, trying to get the volumen for my alexa device called 'Kitchen' this is what I get:

`$ ./alexa_remote_control.sh -d Kitchen -z`
`get volume for dev:Kitchen type:xxxxxxx serial:xxxxxxxxxxxxxxxxx`
`null`

Also, if I try -q command with any device, I get:

`{"message": "Device is not connected/initialized: deviceSerialNumber=G09xxxxxxxx35C6, deviceType=A32xxxxxxx6DTXA"}`

The project is awesome. Thank you for sharing with the community.
Any help would be greatly appreciated.

**Comment by Shirk** [comment]
Same issue here - none of the commands do anything despite saying they have been send.
I can query the list of my Alexa devices however if I query any of them I get this:

```bash
./alexa_remote_control.sh -d Alice -q
queue info for dev:Alice type:AXXXXXXXXXXP serial:GXXXXXXXXXXXXXXG
```
```json
{
  "playerInfo": {
    "hint": null,
    "infoText": null,
    "isPlayingInLemur": false,
    "lemurVolume": null,
    "lyrics": null,
    "mainArt": null,
    "mediaId": null,
    "miniArt": null,
    "miniInfoText": null,
    "playbackSource": null,
    "playingInLemurId": null,
    "progress": null,
    "provider": null,
    "quality": null,
    "queueId": null,
    "state": null,
    "template": null,
    "transport": null,
    "upNextItems": null,
    "volume": null
  }
}
{
  "message": "Device is not connected/initialized"
}
{
  "queueInfo": {
    "header": null,
    "media": null,
    "nextPageToken": null,
    "previousPageToken": null,
    "queueType": null
  }
}
```

I did try to delete the /tmp/.alexa.* files a few times as well as logging in with either a refresh token or by setting EMAIL/PASSWORD/MFA_SECRET. Seeing this for a German account.

**Comment by adn77** [comment]
This is probably related to some missing cookie. See here https://github.com/thorsten-gehrig/alexa-remote-control/issues/148#issuecomment-948040619
