### ISSUE TITLE
USE_ANNOUNCEMENT_FOR_SPEAK  usage unclear

### ISSUE THREAD

**Issue by clach04** [thorsten-gehrig/alexa-remote-control#103]
From readme and comments, it looks like USE_ANNOUNCEMENT_FOR_SPEAK  (not available in the plain shell script version), allows multi-device/room announcements. I can not figure out how to make this work.

It looks like it needs to be set to a positive integer value, but I'm unclear on command line arguments. Everything I've tried has defaulted to single announcement on the oldest device.

`-d ALL`, works the same as without the setting set, each speaker is done in turn.

`-m` with a named group same behavior

**Comment by adn77** [comment]
You have to set this up  for your Echo devices in the Alexa app first (Device Settings -> Communication -> Announcements = On)

If `USE_ANNOUNCEMENT_FOR_SPEAK` is set to  something >0 then you can just use `-d <multi_room_group> -e speak:hello` and the speak command should be output everywhere synchronously.

**Comment by clach04** [comment]
Thanks @adn77 - that's what I needed. I tried so many combinations with this I must have lost track at some point.

I opened https://github.com/thorsten-gehrig/alexa-remote-control/pull/104 as I ran the plain version today, even though I know its not supported! 😆

Re-cap, setting `USE_ANNOUNCEMENT_FOR_SPEAK` is needed and `-d` flag (not `-m`) with a speaker group (not a regular group). I still have one speaker (where verbal announcements work, and announce is enabled, and its in the speaker group) that isn't announcing but the others are.

Running `-a` will list any speaker group names as well as device names.

    echo hello | ./announce_stdin -d YOUR_SPEAKER_GROUP_NAME

Where `announce_stdin` contains:

    #!/bin/sh

    . /home/pi/shell/alexa-remote-control/secrets.sh

    # Example:
    #   echo test from command line | ./announce_stdin -d SPEAKER_GROUP_NAME

    read message
    echo ${message}

    env USE_ANNOUNCEMENT_FOR_SPEAK=1 /home/pi/shell/alexa-remote-control/alexa_remote_control.sh ${*} -e speak:"${message}"

And where `secrets.sh` sets up overrides config (sample American-English config):

    export EMAIL='your@email.here.com'
    export PASSWORD='your passwod here'
    export MFA_SECRET='your 2fa scret here'
    export LANGUAGE='en-US'
    export TTS_LOCALE='en-EN'
    export AMAZON='amazon.com'
    export ALEXA='pitangui.amazon.com'
