### ISSUE TITLE
"alex play song"

### ISSUE THREAD

**Issue by pnathan** [thorsten-gehrig/alexa-remote-control#105]
Now that Amazon has disabled controlling music from my *browser*, is there any way to remote control it with this script? I fear the answer is "no they killed the API", but I want to validate it. 

my invocations of `-s` are returning `{"message":null}`.

**Comment by Apollon77** [comment]
Can the Alexa App on mobile device still can do it? When was this change?

**Comment by pnathan** [comment]
App yes, browser no.


Regards,
Paul

**Comment by Apollon77** [comment]
then - at least in general - the API should still work.

**Comment by adn77** [comment]
@pnathan I rarely use that feature myself.
By looking up an artist and an album in the Amazon Music app (I am not using Unlimited) this works for me:
 `/alexa_remote_control.sh -d Arbeitszimmer -s 'Band Of Horses' 'Acoustic at The Ryman (Live)'`

But even if it wouldn't work anymore, the new `-e textcommand:'Play Music by Band of horses from my library'` should get you a similiar result.
