### ISSUE TITLE
Set a Custom Action in an Alexa Routine

### ISSUE THREAD

**Issue by DunkanA** [thorsten-gehrig/alexa-remote-control#108]
Really love this script as an extension to my HA.  Thanks so much.

I've noticed that Alexa (in the UK) now lets you add a custom command string to Alexa routines.  It might not be available in all countries.  Is this something that could be added to your script, or has this function not been exposed yet?

(https://www.amazon.com/gp/help/customer/display.html?nodeId=GLXY7RFX3L5GH2VR)
https://www.reddit.com/r/amazonecho/comments/jfzgyk/custom_actions_in_routines_have_appeared_at_least/

For now, I create a routine and then ask your script to run the routines.  This allows me to add an option to a Skill, ie "Ask the BBC to play Radio 4" which gets round the BBC Sounds restriction here in the UK.  I can even set night-time radio via "Ask the BBC to play Radio 4 for 30 minutes".

It would be nice if I could pass the custom command directly from your script.

**Comment by Apollon77** [comment]
Can you create such a routine and then read out all routines via ere (I think there was a debug thingy ?!) so that we see how that needs to look like in the routine command?

**Comment by DunkanA** [comment]
ere? I'm not sure I've encountered that

**Comment by Apollon77** [comment]
maybe delete https://github.com/thorsten-gehrig/alexa-remote-control/blob/master/alexa_remote_control.sh#L648 and then provide the content of the "${TMP}/.alexa.automation file ... with the name of a such created routine we should see how it needs to be structured :-)

**Comment by DunkanA** [comment]
Done that.

File is 36K in size, do I just paste it in this thread? or do you want me to cut out a relevant section ("@type": "com.amazon.alexa.behaviors.model.Automation", .... )

Also it looks like I should remove sensitive data, ie customerId, marketplaceId, deviceSerialNumber and id.  Is there any other data I should hide?

**Comment by Apollon77** [comment]
I'm the developer of the nodejs alexa2 package and ioBroker plugin. You could also send it to me via email (iobroker@fischer-ka.de) and I will cut out the relevant parts and provide here. and yes Ids you can replace

**Comment by DunkanA** [comment]
Sent, thanks for looking into this

**Comment by Apollon77** [comment]
```
{
        "@type": "com.amazon.alexa.behaviors.model.Automation",
        "automationId": "xxxxx",
        "name": "Radio 4",
        "triggers": [
            {
                "payload": {
                    "customerId": "??????????????",
                    "utterance": "radio four",
                    "locale": "en-GB",
                    "marketplaceId": "??????????????"
                },
                "id": "xxxxx",
                "type": "CustomUtterance",
                "skillId": "amzn1.ask.1p.customutterance",
                "timeLapse": null,
                "presentationDataList": null,
                "imageUrl": null,
                "clientData": null,
                "context": null
            }
        ],
        "sequence": {
            "@type": "com.amazon.alexa.behaviors.model.Sequence",
            "sequenceId": "xxxxx",
            "startNode": {
                "@type": "com.amazon.alexa.behaviors.model.OpaquePayloadOperationNode",
                "nodeState": null,
                "name": null,
                "type": "Alexa.TextCommand",
                "skillId": "amzn1.ask.1p.tellalexa",
                "operationPayload": {
                    "customerId": "??????????????",
                    "deviceType": "ALEXA_CURRENT_DEVICE_TYPE",
                    "deviceSerialNumber": "ALEXA_CURRENT_DSN",
                    "text": "ask bbc to play radio 4",
                    "locale": "en-GB"
                },
                "presentationDataList": null,
                "clientData": null,
                "context": null,
                "tag": null
            }
        },
        "owner": {
            "@type": "OwnerId",
            "ownerType": "CUSTOMER",
            "id": "??????????????"
        },
        "clientAlias": null,
        "condition": null,
        "status": "ENABLED",
        "creationTimeEpochMillis": 1607615806838,
        "lastUpdatedTimeEpochMillis": 1607615806838
    },
```

**Comment by Apollon77** [comment]
BTW: also works in germany (and with correct locale set to german), even with not beoing available in the App

**Comment by DunkanA** [comment]
> @DunkanA please have a try!

Works great, thanks very much @adn77.  This is a big enhancement, offering many possibilities. :-)
