### ISSUE TITLE
Remove devices?

### ISSUE THREAD

**Issue by giggo** [thorsten-gehrig/alexa-remote-control#113]
I can get the list of devices just fine.
Is there a way to remove one or multiple devices from Alexa?

**Comment by Korki67** [comment]
Hi there, 

I think you just remove it in the Alexa app on your smartphone. After some time, the change will be visible with "-a" option here. If it does not, log off and on again. That pulls the device list.

Its same with changing the name of a device. It takes quite some time until visible here. Even logging off and on did not always work for me to grab the new name of the existing device.

Regards,
Horst

**Comment by adn77** [comment]
Deleting /tmp/.alexa.devicelist* will force the script to re-download the devices. 
But I'm not sure that'S what @giggo was asking...
