### ISSUE TITLE
all of the sudden ERROR: no such utterance. Routines can not be found

### ISSUE THREAD

**Issue by Wayen2000** [thorsten-gehrig/alexa-remote-control#116]
Since today routines can not be found via script anymore. Via app and echo they are still work. The script only shows
ERROR: no such utterance

**Comment by Dizzy1985** [comment]
Hi there. Since tonight I have also had the problem that no more routines can be recognized / triggered by the script. The rest of the functions of the script work perfectly. Only the routines can no longer be executed. In the Alexa app I checked the functionality of the routines several times.

**Comment by Apollon77** [comment]
When you open your alexa mobile app ... are your routines still listed there? If no ... Amazon broke stuff and it normally fixes itself within 1-2 days

**Comment by Dizzy1985** [comment]
The routines are visible in the Alexa app and can also be executed. (Via app)
No routines can be found on the alexa.amazon.de (website) or none are displayed.

**Comment by pschild** [comment]
Hi,
I can confirm - I'm having the same issue since a few hours.
For example, `speak` commands are still working, but `automation` commands are failing.
Guess that Amazon maybe changed their API?

**Comment by Apollon77** [comment]
Yes it seems that Amazon changed stuff ...

**Comment by adn77** [comment]
The endpoint appears to have changed to `api/behaviors/v2/automations`.
I bumped to v0.17b to reflect this change.
