### ISSUE TITLE
TuneIn Radio setting not working anymore

### ISSUE THREAD

**Issue by Korki67** [thorsten-gehrig/alexa-remote-control#119]
Hi there,

I was using the script for long time without issues. Now, "-r station-name" does give error messages:

sudo -u www-data ./alexa_remote_control.sh -d mydevice -r swr3

**jq: error (at <stdin>:0): Cannot iterate over null (null)
ERROR: no Station "" found on TuneIn**

I did log off and on again. I did apt-get update & upgrade. I did reboot. I can make Alexa speak any text, so most interfaces are still working. So my MTA etc are all OK. Just setting -r not working. Not with "swr3" and not with "1live" which I used before. I am getting suspicious that Amazon changed something on their side. In this case, we should all have the same issue ...

Anybody having same issue? And possibly solved?

Regards,
Horst

**Comment by adn77** [comment]
This is due to TuneIn requiring some additional Serial when using their API. This could probably be implemented...

Using the new TextCommand "play swr3 on Tunein" is a good substitute though.

**Comment by Korki67** [comment]
Hello Alex,

sorry, I don't get the textcommand working. The script reports:

sending:cmd textcommand: play swr3 on Tunein to dev:mydevice type:.... serial:.... customerid:......
Skipping unsupported command: textcommand: .......

I am using the current script from Github.
As my Alexa is set to German, I also tried "spiele swr3" or "spiele swr3 von tunein"

All tries give error message above and no radio on the echo.
What am I doing wrong?

Regards,
Horst

**Comment by adn77** [comment]
@Korki67 I tried the TuneIn API today and it returned the proper station id:
`https://api.tunein.com/profiles?fullTextSearch=true&query=swr3`

I don't know if they changed their API back - but it should be working. Please test it using alexa_remote_control.sh

Alex

**Comment by Korki67** [comment]
Hi Alex, yes it is working again at no change on my side. Thanks for your support. Regards, Horst
