### ISSUE TITLE
Any chance for starting routines?

### ISSUE THREAD

**Issue by CarJu** [thorsten-gehrig/alexa-remote-control#12]
Hello!
Now we can configure own texts in routines which alexa will say...
It would be a great feature, when we now can start a routine with your script!

Greethings
Carsten

**Comment by adn77** [comment]
That would be absolutely incredible and one of the most-asked-for feature so far.

As we can only use the reverse engineered API calls, we'll have to wait a bit until the routines start showing up in the Alexa web-frontend...

Alex

**Comment by adn77** [comment]
I just pushed a new version which should be able to execute a pre-defined routine.

`alexa_remote_control.sh -d Esszimmer -e automation:"Wakeup Call"`

Due to the heavy involvement of 'jq' for JSON parsing, there is no _plain_ version with that feature.

Alex

**Comment by mister-extra** [comment]
I'm  a little confused - I can use the speak option with the plain version ? this feature is absolutely great !

**Comment by adn77** [comment]
Only the automation feature is exclusive to the "full" version.
The speak option also works with the "plain" version.

**Comment by mister-extra** [comment]
ok  - I'm  sorry - automation means routines - really cool and thank you for sharing
