### ISSUE TITLE
-e textcommand not working

### ISSUE THREAD

**Issue by Korki67** [thorsten-gehrig/alexa-remote-control#121]
Hi there,

I found out that the textcommand cannot play radio on a "stereo pair" of 2 Echos. 
This is the error message which is not very obvious to understand:

sudo -u www-data ./alexa_remote_control.sh -d mypair -e textcommand:'play swr3 on Tunein'

sending:cmd textcommand: play swr3 on Tunein to dev:mydevice type:.... serial:.... customerid:......
Skipping unsupported command: textcommand: .......

I have two Echo called A1 and A2. Both linked to a stero pair called "mypair".
Sending the text command to A1 device works fine. To mypair fails as above.

Item can be closed. Scripts -h could be extended to avoid pairs on textcommand.

Regards,
Horst

**Comment by adn77** [comment]
I haven't actually used the _textcommand_ to play TuneIn (although I suggested to you to do the very same :D)...

I will have a look into the way how devices are specififed for _textcommand_. For now, please try the textcommand `play swr3 on tunein on mypair` without further specifiying a device on the command line.
