### ISSUE TITLE
How to send a voice message to 2 and ALL Echo's

### ISSUE THREAD

**Issue by dcaccount** [thorsten-gehrig/alexa-remote-control#123]
Hello,
I am kindly asking you for small help as I have not been able:

1) send the same message to two Echo's at the same time. I have tried:
`alexa_remote_control.sh -d 'Echo 1' 'Echo 2' -e speak:'message'

but it not working.
How can I achieve that?

2 send the same message to ALL Echo's

Thanks for helping,
Dan

**Comment by Korki67** [comment]
Hi Dan,

option -d accepts only 1 device or group. In the alexa app you can pair 2 echos to a stereo pair with a new device name. Some commands allow a stereo pair as device, some do not. So if a command does not accept a stereo pair, try one of the 2 devices in the -d option.

There is a special device -d ALL. This will apply the command to all your echos. This I am using and it works easily.

Futhermore, you can define multiroom devices. This is from the -h help of the script:

purpose  -m : delete multiroom and/or create new multiroom containing devices
syntax     -m <multiroom_device> [device_1 .. device_X]

So you create your new multi-device with a new name and then it can be used for -d option.

Regards,
Horst

**Comment by dcaccount** [comment]
> Hi Dan,
> 
> option -d accepts only 1 device or group. In the alexa app you can pair 2 echos to a stereo pair with a new device name. Some commands allow a stereo pair as device, some do not. So if a command does not accept a stereo pair, try one of the 2 devices in the -d option.
> 
> There is a special device -d ALL. This will apply the command to all your echos. This I am using and it works easily.
> 
> Futhermore, you can define multiroom devices. This is from the -h help of the script:
> 
> purpose -m : delete multiroom and/or create new multiroom containing devices
> syntax -m <multiroom_device> [device_1 .. device_X]
> 
> So you create your new multi-device with a new name and then it can be used for -d option.
> 
> Regards,
> Horst

Thanks Horst,
very kind of you.

Can you please give me an example of creation of a multi room device? Syntax is not very clear to me

**Comment by Korki67** [comment]
Hi Dan,

USE_ANNOUNCEMENT_FOR_SPEAK is set in line 131 of the script to "0" = deactivated.
"speak" just means that one specified echo does say something.
"announce" means that one text is sent to several echos.
To "set it" means to change the value from "0" to "1".
This will make the script use "announce" when you ask to "speak".
That in turn will allow a group of devices to say something.

This is how I understand the help output of the script
and the comments inside the script up to line 133.
I have not yet used it. You need to experiment with it.

I am not sure USE_ANNOUNCEMENT_FOR_SPEAK is needed for ALL.
My USE_ANNOUNCEMENT_FOR_SPEAK is "0" and ALL is working.
I assume "notifications" are enabled via the Alexa App.
So to make -d ALL working, first look into the App
how to enable notificaitons. If something like that is
disabled and you can enable it, try it and test -d ALL.

Regards,
Horst

**Comment by adn77** [comment]
Thanks @Korki67 for jumping in! 

@dcaccount the easiest option for creating a multi-room group is by using the Alexa app on your mobile.
You must not use the reserved `ALL` as a name for the group!

The difference between using a multi-room device vs. using the (script) internal `ALL` device is that the latter simply runs the specified command sequentially on every existing Echo device. While the former can use the _announcement_ feature of Alexa to play commands (like speak) synchronously on each Echo device.

In order to use announcements, you have to enable them in the Alexa app (Devices => Communication) for each device and then set `USE_ANNOUNCEMENT_FOR_SPEAK=1` in the script.

**Comment by Korki67** [comment]
Hello Alex,

to avoid users create a multiroom device called ALL, the next issue of the script could have this update:

		-m)
			if [ "${2#-}" != "${2}" -o -z "$2" -o "$(echo "${2}" | tr [:upper:] [:lower:])" = "all" ] ; then
				echo "ERROR: missing or invalid argument for ${1}"
				usage
				exit 1

Regards,
Horst

**Comment by dcaccount** [comment]
> Thanks @Korki67 for jumping in!
> 
> @dcaccount the easiest option for creating a multi-room group is by using the Alexa app on your mobile.
> You must not use the reserved `ALL` as a name for the group!
> 
> The difference between using a multi-room device vs. using the (script) internal `ALL` device is that the latter simply runs the specified command sequentially on every existing Echo device. While the former can use the _announcement_ feature of Alexa to play commands (like speak) synchronously on each Echo device.
> 
> In order to use announcements, you have to enable them in the Alexa app (Devices => Communication) for each device and then set `USE_ANNOUNCEMENT_FOR_SPEAK=1` in the script.

Fist of all thanks to all for your replies.

Unfortunately I have not been able to create a group using the -m option. I have "Echo sala" and "Echo cucina" and I would like to group them in a group called "UpAndDown".

I tried:
`alexa_remote_control.sh -m UpAndDown 'Echo sala' 'Echo cucina' 'Echo cantina'`
but I got the error:

> Creating multi room dev:UpAndDown member_dev(s): Echo/ sala Echo cucina Echo cantina
ERROR: unkown device dev:Echo/

Any idea, where am I wrong?

Then, I set `USE_ANNOUNCEMENT_FOR_SPEAK=1` in the script, I have enabled the announcements in the Alexa app, but when I try to:
`./alexa_remote_control.sh  -e speak:'hello' `
it does reproduce only from one Echo.

Any idea? Please help.
Thanks,
Dan

**Comment by Korki67** [comment]
Buona Sera Dan,

this is how I assume it will work:

`./alexa_remote_control.sh -m UpAndDown sala cucina
./alexa_remote_control.sh -d UpAndDown -e speak:"Buon giorno a tutti.'`

I think you will see the difference and understand why your commands could not work.

Regards,
Horst

**Comment by dcaccount** [comment]
Thanks everybody for the help!
