### ISSUE TITLE
Question on volume

### ISSUE THREAD

**Issue by dcaccount** [thorsten-gehrig/alexa-remote-control#127]
Hello,
I would like to reproduce one text at a given volume, for instance 100, without changing the default volume of the Echo.

I have not understood how to do that, can you please help?

Shall I add any instruction to the following command:

`alexa_remote_control.sh -d 'Kitchen' -e speak:'hello'`

Thanks,
Dan

**Comment by xg6968** [comment]
Hello,

vol = 50% 

alexa_remote_control.sh -d "Echo salon"  -e vol:50

**Comment by dcaccount** [comment]
> Hello,
> 
> vol = 50%
> 
> alexa_remote_control.sh -d "Echo salon" -e vol:50

Thanks!

**Comment by adn77** [comment]
@dcaccount 

This should set the volume for the speak command only:
`SPEAKVOL=100 alexa_remote_control.sh -d 'Kitchen' -e speak:'hello'`

The comand tries to find the current volume before setting the volume for the speak command, and returns to that after the speak completed.

**Comment by dcaccount** [comment]
> @dcaccount
> 
> This should set the volume for the speak command only:
> `SPEAKVOL=100 alexa_remote_control.sh -d 'Kitchen' -e speak:'hello'`
> 
> The comand tries to find the current volume before setting the volume for the speak command, and returns to that after the speak completed.

Thanks!
