### ISSUE TITLE
Let Alexa start a conversation from the script?

### ISSUE THREAD

**Issue by gestein126** [thorsten-gehrig/alexa-remote-control#128]
Hello,
I am searching for a possibility to let Alexa say something like "Your vacuum cleaner is scheduled to start now. Would you like to stop it?".
Alexa should then wait for some seconds to let one say "yes", "no" or nothing.
The script should then return "yes" or "no" (or something like this).

Would this be possible?
Thanks a lot for every help.
Gerhard

**Comment by Korki67** [comment]
Dear Gerhard,

info: I am not involved into development of the script in here. I am just an experienced user.

What you are looking for, is Alexa skill development. This is complex item: Alexa skill, ngrok, perl object code are some keywords. I actually managed to get such a skill working. If you are new to this kind of programming, you will need several days full of frustration until a "hello world" succeeds. After this, items like your idea will be simple.

The script in here cannot receive and analyse answers. The great thing about the script in here is that it totally shortcuts the complex item of skill development.

Regards,
Horst

**Comment by DunkanA** [comment]
Gerhard

Again, I'm just a fan of alexa-remote-control

If you have a Home Automation product (I use Domoticz) and HA-Bridge.  You could rig up some code (XYZ) to issue the question, wait a few minutes and see if a stop request was issued.  If no stop request then start the vacuum.  The Stop request would be triggered separately (I usually use Alexa routines) to set a Home Automation variable via HA-Bridge.  This variable is queries by the code (XYZ) before starting the vacuum.

**Comment by Apollon77** [comment]
Making Alexa "Listening" and process the feedback is only passible using Skills or maybe these custom "Blueprints". Nothing that this script is able to do. I would close as "not possible"

**Comment by gestein126** [comment]
Thanks a lot for your answers.
At least I do have new possibilities now to let the search continue ;-)

Thanks and best regards
Gerhard

**Comment by adn77** [comment]
@gestein126 your best bet is @DunkanA 's suggestion:
1.) create Automation "yes" that turns on state of HA-Bridge device
2.) create Automation "no" that turns off state of HA-Bridge device
3.) issue the question - set HA-Bridge device state to false
4.) the answer has to be something like: "Alexa, yes/no" triggering your automation

For anything more natural you'd have to look into Alexa Skills as @Apollon77  mentioned - there might be a skill authored by your favorite HomeAutomation software that lets you do what you're up to.
