### ISSUE TITLE
-e speak not working anymore

### ISSUE THREAD

**Issue by Korki67** [thorsten-gehrig/alexa-remote-control#129]
Hi there,

since some time, -r radio was not working anymore and we used the new -e textcommand as a workaround.

I just realised that -e speak is also not working anymore. The script returns a nice looking message but Alexa stay silent.

We can again use -e textcommand:"Sprich mir nach: bla bla bla". Unfortunately, the quality is very poor because e.g. a full stop is just skipped. The text does not sound natural at all and is sometimes very hard to understand. Even worse, HTML style syntax of SSML is not interpreted but even partially spoken.

So whereas the workaround for -r is very much OK, the use of textcommand:"Sprich mir nach: ..." is poor.

Sorry that "Sprich mir nach" is German for kind of "listen and repeat". 

@adn77 I think many would be greatfull if you could find a better way than textcommand. My Flask "return statement" seems to continue to work as before at perfect Alexa quality. So there still is a way ... beyond my skills.

Regards,
Horst

**Comment by Apollon77** [comment]
When speak is not working using the script please try via alexa app. If it is also not working there it is caused by the device or amazon

**Comment by Korki67** [comment]
Hello Apollon,

Flask is working from same Raspi and also the App can speak as usual. Only from script nothing happens. I can logoff, logon again, list devices by -a etc all working. Also textcommand is working.

Updates are rolled out over a certain period of time. It may be that I got an update others don't have yet. Is -e speak: still working for you?

Regards,
Horst

**Comment by Korki67** [comment]
Hi there, my -e speak is working again. I have no clue what happened. This item can be closed. Regards, Horst
