### ISSUE TITLE
Get and return voice response to stdout

### ISSUE THREAD

**Issue by petrasl1976** [thorsten-gehrig/alexa-remote-control#131]
Would be really great feature if this script would return human voice response to Alexas question. Something similar to bellow command in the shell:

`read -p "Do you want me to close the curtains? " ans && echo $ans`

In home automation there are cases when i would prefer to be asked instead of perform always the same scenario. Lets say, if i ask Alexa to start my projector, i would like Alexa asks me back "Do you want me to close the curtains?" and based on my answer different automation actions would be performed.

It would be useful for reminders too. Lets say we have scheduled phrase to say "Does **your puppy name** got his breakfast?" every morning and it will repeat each 10 mins until someone responds to Alexa "yes".

With such functionality dialog with alexa would be more natural than "Alexa, turn off puppy reminder" :)

Thanks

**Comment by Apollon77** [comment]
This is only possible using Skills

**Comment by Korki67** [comment]
Hello Petrasl,

I solved that by creating my own skill on AWS. Once the skill in "development status", you can call it. So I call it by "Alexy, frage Wohnung ...." (ask appartment ...). Then I use ngrok on a RasperryPi to catch it and have a Python Flask script handling that.

Unfortunately, skills in development status cannot be used in Routines, so calling your own skill cannot be simplified.

This approach needs kind of a nerd's mind and patience, I admit. I am not very skilled in this environment and I think I needed 2 nights to get it working.

Regards,
Horst
