### ISSUE TITLE
/home/pi/domoticz/scripts/alexa_remote_control.sh: 626

### ISSUE THREAD

**Issue by lukiifaz** [thorsten-gehrig/alexa-remote-control#134]
pi@raspberrypi:~ $ /home/pi/domoticz/scripts/alexa_remote_control.sh -a
cookie does not exist. logging in ...
device list does not exist. downloading ...
the following devices exist in your account:
/home/pi/domoticz/scripts/alexa_remote_control.sh: 626: /home/pi/domoticz/scripts/alexa_remote_control.sh: jq: not found

pi@raspberrypi:~ $ /home/pi/domoticz/scripts/alexa_remote_control.sh -d ALL -e speak:'hello'
/home/pi/domoticz/scripts/alexa_remote_control.sh: 1144: /home/pi/domoticz/scripts/alexa_remote_control.sh: jq: not found

**Comment by adn77** [comment]
looks like "jq" is not in your PATH
