### ISSUE TITLE
Speak SSML?

### ISSUE THREAD

**Issue by kfishermail** [thorsten-gehrig/alexa-remote-control#136]
It appears -e speak: will 'speak' SSML,  I cant get it to work, can anyone give me an example?

**Comment by adn77** [comment]
alexa_remote_control.sh -e speak:"<speak><voice name='Hans'>Hallo ich bin Hans</voice><audio src='soundbank://soundlibrary/musical/amzn_sfx_trumpet_bugle_03'/> und ich bin Alexa</speak>"
