### ISSUE TITLE
Speak SSML

### ISSUE THREAD

**Issue by kfishermail** [thorsten-gehrig/alexa-remote-control#137]
Can the -e:speak Command use SSML

alexa_remote_control.sh -e speak:"Hallo ich bin Hans und ich bin Alexa"
works, but:
alexa_remote_control.sh -e speak:"<speak>Hallo ich bin Hans und ich bin Alexa</speak>"
does not

It appears -e speak: will 'speak' SSML, I cant get it to work, can anyone give me an example?

**Comment by christianTF** [comment]
I can't see the difference of your examples.

**Comment by kfishermail** [comment]
It looks like my email client or something is stripping out the XML tags of SSML

Try this, I have replaced '<' with '!'

!speak>
     Mary had a little lamb !break time="3s"/>Whose fleece was white as snow.
!/speak>

To clarify, I want the -e speak command to interpret SSML, 
See the followink link
https://docs.aws.amazon.com/polly/latest/dg/supportedtags.html
