### ISSUE TITLE
ssml

### ISSUE THREAD

**Issue by kfishermail** [thorsten-gehrig/alexa-remote-control#138]
It looks like my email client or something is stripping out the XML tags of SSML

Try this, I have replaced '<' with '!'

!speak>
Mary had a little lamb !break time="3s"/>Whose fleece was white as snow.
!/speak>

To clarify, I want the -e speak command to interpret SSML,
See the followink link
https://docs.aws.amazon.com/polly/latest/dg/supportedtags.html

**Comment by adn77** [comment]
Sorry I should've put my comment in code:

`alexa_remote_control.sh -e speak:"<speak><voice name='Hans'>Hallo ich bin Hans</voice><audio src='soundbank://soundlibrary/musical/amzn_sfx_trumpet_bugle_03'/> und ich bin Alexa</speak>"`

**Comment by kfishermail** [comment]
I tried your command, and alexa said
 "sorry i am having a problem accessing your simon says skill right now"
Any ideas?
I am using        'alexa-remote-plain.sh'

just to verify. your command works on your system?
I tried to enable simon says skill, but i did noy know which one?

**Comment by adn77** [comment]
Sorry, I didn't read your message properly :(
The plain version is no longer supported as it is really hard to do JSON processing without JQ.

The above line was tested with the full version.

**Comment by kfishermail** [comment]
That fixed it, thanks
