### ISSUE TITLE
Refresh token not working ...

### ISSUE THREAD

**Issue by Korki67** [thorsten-gehrig/alexa-remote-control#143]
Dear Alex, dear all,

I used the refresh_token on win64. I could login to Amazon through 8080. Output was:
> Error: You can try to get the cookie manually by opening http://localhost:8080/ with your browser. / null

I tried to re-open the browser on 8080 but it was just waiting for ever … In the line below the error, I got the token anyway:
> Atnr|Abcd and so on ….

So I copied all incl. the “Atnr|” into the script. Didn’t work. I added my email and my password, still not working.
I also tried the refresh token without the “Atnr|” without success. This is output of alexa_remote_contro.sh -a or -login:
> cookie expired, logging in again …
> ERROR: cookie retrieval with refresh_token didn’t work

I created the token on win64 and use it on a RaspiPi.
The same RaspiPi worked before with MFA which stopped working.

I would appreciate any proposal how to get it working

Regards,
Horst

**Comment by adn77** [comment]
Check the string length of your token. Mine looks like this:

`Atnr|EwXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXX`

**Comment by Korki67** [comment]
I am using a German account with amazon.de

Length exactly same, pattern is different:

Atnr|EwXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_XXXXXXXXXXXXXX_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_XXXXXXXXXXXXXXXXXXXXX_XXXXXXXXXXXXXXXXXXXXXXXXX-XXXXX
Atnr|EwXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXX

I have compared first and last chars and they are same ....
