### ISSUE TITLE
[Minor] some chars are not read

### ISSUE THREAD

**Issue by LordDarkneo** [thorsten-gehrig/alexa-remote-control#149]
Hello and thank you for your great job on this plugin!

I made it worked as I wanted to (i.e. executing remote scripts from my domoticz instance to execute scripts). 

I just discovered 1 char that is not interpreted by my remote command: " ' ". For instance, when I execute the script locally by:
`alexa_remote_control.sh -e speak:"You're great"
`
It is working worrectly. But when executing my remote command:
`ssh alexa_remote_control@123.123.123.123 /home/user/alexa-remote-control/alexa_remote_control.sh -e speak:"You're great"
`
The command is not executed and I have a ">" display on the ssh screen....

Any chance to have a quick support on this? 

Thanks four your help!

Regards

**Comment by adn77** [comment]
This is how the shell invoked by ssh handles quotes.
You could try escaping `"You\'re great"`

**Comment by LordDarkneo** [comment]
Thanks for your reply and sorry for my late answer (wasnt home, si couldnt test). 

The \ char is not escaping.... I'm now having the error:
`great: -c: line 0: unexpected EOF while looking for matching `''
great: -c: line 1: syntax error: unexpected end of file

`
Moreover, it seem like the space between wirds is also stopping the command (I gave a try with other scripts)
