### ISSUE TITLE
how to use "sound:<soundeffect_name>"

### ISSUE THREAD

**Issue by Korki67** [thorsten-gehrig/alexa-remote-control#152]
Hi there,

I have tried some names like "soundbank://soundlibrary/air/fire_extinguisher/fire_extinguisher_05" and some truncations of it, but don't get any sounds.

Could someone let me have an example or some more info?

Regards,
Horst

**Comment by sammyke007** [comment]
These work for me:

bash alexa_remote_control.sh -d Zolder -e sound:air_horn_03
bash alexa_remote_control.sh -d Zolder -e sound:bell_02
bash alexa_remote_control.sh -d Zolder -e sound:boing_01
bash alexa_remote_control.sh -d Zolder -e sound:amzn_sfx_trumpet_bugle_04
bash alexa_remote_control.sh -d Zolder -e sound:amzn_sfx_crowd_applause_01
bash alexa_remote_control.sh -d Zolder -e sound:amzn_sfx_doorbell_01
bash alexa_remote_control.sh -d Zolder -e sound:amzn_sfx_doorbell_chime_01
bash alexa_remote_control.sh -d Zolder -e sound:amzn_sfx_doorbell_chime_02
bash alexa_remote_control.sh -d Zolder -e sound:amzn_sfx_scifi_alarm_04

**Comment by Korki67** [comment]
Cool, those work for me as well. Thanks a lot!
I will close the item.

**Comment by sammyke007** [comment]
More good news. I started looking into this again today tnx to your post and now everything works!

You just have to use -speak instad of -sound! U can now use every sound available and even combine it with speech (TTS) or multiple sounds in one command! eg:

bash alexa_remote_control.sh -d Zolder -e speak:'<audio src="soundbank://soundlibrary/scifi/amzn_sfx_scifi_timer_beep_01"/>'

bash alexa_remote_control.sh -d Zolder -e speak:"<speak>Please disarm<audio src='soundbank://soundlibrary/alarms/beeps_and_bloops/timer_01'/><audio src='soundbank://soundlibrary/alarms/beeps_and_bloops/timer_01'/></speak>"

GREAT!

**Comment by Korki67** [comment]
Cool. Thanks again.
