### ISSUE TITLE
Seems answer from "-lastalexa" is changed by Amazon

### ISSUE THREAD

**Issue by Korki67** [thorsten-gehrig/alexa-remote-control#156]
Dear all,

since a few hours my scripts fail to work and I found the root cause.
This is the new answer from -lastalexa:

old: Name1
new: Name1=XXXXXXXXXXXXXXX=YYYYYYYYYYYYYYYY=ECHO

Herein, the XX and YY are codes of capital letters and digits.
"Name1" is the name of the last alexa used.

I am now changing my script to split the string by = and use first element.
I assume all who use -lastalexa need to do that sooner or later.

Regards,
Horst

**Comment by adn77** [comment]
Sorry, my bad. I introduced that breaking change some time ago as there might be devices named the same (Name1).
This happens especially if you use Alexa on your mobile or some other non-Amazon device.

The field names are:
`<accountName>=<deviceType>=<serialNumber>=<deviceFamily>`

Alex

**Comment by Korki67** [comment]
perfect, thanks. Strange that it just occured here even though I did not update your script. Be it what it may ... item is easy to solve once one is aware of the item. Solved and Closed with thanks.
