### ISSUE TITLE
<InternalFailure/> from Play & Pause // parse error from jq?

### ISSUE THREAD

**Issue by Korki67** [thorsten-gehrig/alexa-remote-control#162]
Hi there,

**1) InternalFailure**
Since Sept 4th at 02:53 in the morning I get an error `<InternalFailure/>` on play and pause commands from Amazon. The error occurs often but not always. I used "textcommand" as workaround. Anybody having same issue or solution?

**2) parse error**
I also get this from -q (query queue): `parse error: Invalid numeric literal at line 2, column 0`. I was logging standard output, not error, so this was not logged until now. It may have started at same time as error 1) above, I am not sure. It is send by the alexa script and I assume the parse error is from jq? I have not changed anything as far as I am aware of. I have no idea what to do.

Any hints / ideas or feedback on same issues elsewhere would be great!

Regards,
Horst

**Comment by adn77** [comment]
Looks like those are `/api/np/*` endpoints. Possibly something is changing there.
(The parse error is jq trying to parse `<InternalFailure/>`).

I'll check if I can find out what Amazon is using instead nowadays.
Thanks for reporting the issue!

**Comment by adn77** [comment]
I just checked the Alexa App, Pause isn't working there either - looks like they broke something.
Let's be patient and observe if it just returns to normal within a few days :)

**Comment by Korki67** [comment]
Cool. I will include the App into my test procedure in the future. Thanks so much!

**Comment by Apollon77** [comment]
I would wait for now ... lets see when Amazon fixes it ... and in fact contact Amazon supprt about the issues in App and voice :-)

**Comment by Korki67** [comment]
yes, also working here nicely again. Item can be closed.
