### ISSUE TITLE
Can't get the script to speak

### ISSUE THREAD

**Issue by elpekenin** [thorsten-gehrig/alexa-remote-control#164]
Hey, I know this is a recurrent question but previous posts I've read didn't fix my issue.

I found this tool when researching how to get my Alexa talking upon certain events, and went ahead to configure it. Idea is to trigger the script from Python/Javascript/wherever neeed.

*Note: Only used terminal by hand so far*
I've used alexa-cookie (not the binary, but running the server myself) to get my REFRESH_TOKEN, and placing it on the script results on a succesfull login (`./alexa.sh -a` lists both my Echo Show's).

However I've been trying these last 2 days to get the script to talk and couldnt achieve anything, did I perhaps miss some configuration step (likely on the Amazon account/device part of things) or some limitation?? 

Command seems to output a success
```
$ ./alexa.sh -e speak:Hola
setting default device to: Echo Show de HIMTAE
sending cmd:speak:Hola to dev:Echo Show de HIMTAE type:A4ZP7ZC4PI6TO serial:XXX customerid:XXX
```

**Comment by Korki67** [comment]
Hello Elpekenin,

please note I am just another user of this great script. Not sure I can help but let's try.
As you can login and see your devices, I think all configuration is good and nothing is lacking.

I am always specifying the device with -d and do not rely on any default device.
As long as you have a problem, I recommend to use -d devicename to be sure.

Try to let Alexa speak while playing music. Does music stop or reduce volume while the device should speak?
Are you sure loudness is high and not zero? I fell into this trap some time ago ... it speaked with volume 0 ... try -z

Sometimes the normal command fails for some time ... no clue why that happens. Must be issues at Amazon.
During such time I replace the command (e.g. -r radio) by textcommand "play radio" as workaround.
You can also try the  workaround -e textcommand:"say Hello". Then the device should also say "Hello".

Option -q gives you a lot of information. Perhaps you glance through it and perhaps you spot something ...

Regards,
Horst

**Comment by Korki67** [comment]
one more idea: are your two devices connected as a stereo pair? If yes, this may be relevant:

my stereo pairs loose the ability to speak every few days.
Also, when I use the Alexa by my normal voice, they don't speak.
Unlinking the pair, disconnect & reconnect power, re-link the pair solves this.
I don't think it is an issue of the script here but an issue of Amazon.

So in case they are a paired stereo device, unpair, reboot and try again....

**Comment by elpekenin** [comment]
Thanks for all the information :)

> I am always specifying the device with -d
- Tried both with and without it, didn't spot any difference

> Try to let Alexa speak while playing music
- Will try ASAP

> Are you sure loudness is high and not zero?
- I'm pretty sure I also sent some "change volume" commands yesterday but can't really recall, will re-check

> textcommand as workaround
- Same as before, pretty sure I tried doing so, but will re-check

> stereo pair
- I don't even knew there was such thing, so most likely they arent

> has a space?
- Yeah it does, will try and remove it

**Comment by Korki67** [comment]
Hi elpekenin,

yeah the link to amazon.com may be issue. I have a German amazon account, and am linked to amazon.de:

`SET_AMAZON='amazon.de'`

Did you try to set your relevant line to amazon.es?

Regards,
Horst

**Comment by elpekenin** [comment]
I did try several configs over the days but i dont really remember then anymore.

Ended up using a Home Assistant integration which worked fine for my needs.
- It can launch my skill without me speaking (not really sure how)
- My skill now reads a variable stored on Home Assistant and says that upon being launched

Thx for the help anyway, closing this :)
