### ISSUE TITLE
Error -lastalexa and -last command

### ISSUE THREAD

**Issue by Lxtxs** [thorsten-gehrig/alexa-remote-control#170]
For 2 days now I've been getting the error message when running the commands -lastalexa and -last command.
parse error: Invalid numeric literal at line 1, column 10
Does anyone else have this problem or is there a solution for it? I tried it on different Linux instances.
Thanks for your help.

**Comment by Korki67** [comment]
Hi Lxtxs,

yes, I get very same error line 1 column 10.
I am connected to amazon.de using refresh-token.

Not obvious to me from the "parse error" is issued.
So no straight clue where to look into.

Regards,
Horst

**Comment by Tloram** [comment]
All apps that were relying om the Alexa activities api is currently experiencing the same issue, because Amazon appear to have retired their Alexa web UI and its corresponding api endpoints.

e.g the Home Assistant Alexa Media Player custom component: https://github.com/custom-components/alexa_media_player/issues/2089

**Comment by Korki67** [comment]
Hi Tloram,

to speak is working fine, e.g. "-d Name -e speak:Hallo" works nicely. So it is not that the API is removed or so ...

I can also ask questions with FLASK and the answer is processed well ...

Seems the answer to -lastalexa has a char that a parser cannot swollow ... perhaps an & or an \ ... who knows.

Would be interesing if someone knows which parser / filter gives the error message.
Perhaps this parser has an options to ignore any strange chars .... and voila ... issue solved?

Regards,
Horst

**Comment by adn77** [comment]
The API endpoint moved here 
/alexa-privacy/apd/rvh/customer-history-records/?startTime=___&endTime=___&recordType=VOICE_HISTORY&maxRecordSize=___

I will try to update this in a week from now.

**Comment by Lxtxs** [comment]
Thank You!!!!

**Comment by ralmulle** [comment]
I have solved our problem so far and updated the functions last_alexa() and last_command() as follows:
```
AMAZON_NEW_API='amazon.de/alexa-privacy/apd/rvh'  #New System Variable für Alexa History

last_alexa()
{
${CURL} ${OPTS} -s -b ${COOKIE} -A "${BROWSER}" -H "DNT: 1" -H "Connection: keep-alive" -L\
 -H "Content-Type: application/json; charset=UTF-8" -H "Referer: https://www.${AMAZON_NEW_API}" -H "Origin: https://www.${AMAZON}"\
 -H "csrf: $(awk "\$0 ~/.${AMAZON}.*csrf[ \\s\\t]+/ {print \$7}" ${COOKIE})" -X GET\
 "https://www.${AMAZON_NEW_API}/customer-history-records?startTime=$(date +%s --date "-24 hours")&endTime=$(date +%s --date "+24 hours")&recordType="VOICE_HISTORY"&maxRecordSize=1" | ${JQ} -r '[.customerHistoryRecords[] | select(.recordType == "VOICE_HISTORY" ) | select(.utteranceType == "GENERAL") | .device[]] | values[0]' 
}

last_command()
{
ACTIVITIES=$(${CURL} ${OPTS} -s -b ${COOKIE} -A "${BROWSER}" -H "DNT: 1" -H "Connection: keep-alive" -L\
 -H "Content-Type: application/json; charset=UTF-8" -H "Referer: https://www.${AMAZON_NEW_API}" -H "Origin: https://www.${AMAZON}"\
 -H "csrf: $(awk "\$0 ~/.${AMAZON}.*csrf[ \\s\\t]+/ {print \$7}" ${COOKIE})" -X GET\
 "https://www.${AMAZON_NEW_API}/customer-history-records?startTime=$(date +%s --date "-24 hours")&endTime=$(date +%s --date "+24 hours")&recordType="VOICE_HISTORY"&maxRecordSize=10")
 
if [ -z "$DEVICE" ] ; then
	echo "$ACTIVITIES" | ${JQ} -r '[.customerHistoryRecords[] | select(.recordType == "VOICE_HISTORY" ) | select(.voiceHistoryRecordItems[].recordItemType == "CUSTOMER_TRANSCRIPT" ) | .voiceHistoryRecordItems[].transcriptText] | values[0]'
else
	echo "$ACTIVITIES" | ${JQ} -r --arg jqdevice "$DEVICE" '[.customerHistoryRecords[] | select(.recordType == "VOICE_HISTORY" ) | select(.device[] == $jqdevice) | select(.voiceHistoryRecordItems[].recordItemType == "CUSTOMER_TRANSCRIPT" ) | .voiceHistoryRecordItems[].transcriptText] | values[0]'
fi
}
```
I don't know if it's the best solution, but it works for my applications.
However, I noticed that it sometimes takes up to 2 seconds for Amazon to update the status in the API.

**Comment by Korki67** [comment]
Hello Ralmulle,

your code works fine for me, thanks a lot. Lastalexa correctly returns the name of the device. 

Previously, it returned device=some_ID_codes. Now, with above code, no "=" and no further code.
As "split" command without split-char "=" returns the full string, my code works without change.

Thanks again!
Horst

**Comment by nodev11** [comment]
Hello ralmulle,

thanks a lot!

> `...startTime=$(date +%s --date "-24 hours")&endTime=$(date +%s --date "+24 hours")...`

To make this work on embedded devices I use the folowing code, to be more portable:

`...startTime=$(($(date +%s)-86400))&endTime=$(($(date +%s)+86400))...`

**Comment by Matthy1810** [comment]
The Code from @ralmulle works, but for me it usually takes around 5 seconds until the last alexa device ist updated.
Ist there a better URL that updates the last alexa device faster?

**Comment by ralmulle** [comment]
That's still my problem too. I haven't found a solution yet.

**Comment by Apollon77** [comment]
Alexa corrently has issues with that API ... also your App might show errors

**Comment by Lxtxs** [comment]
Hello, unfortunately this hasn't worked for a few days. I just get an empty output in the command line. Does anyone have a fix yet?

**Comment by Dar4ide** [comment]
Hey, same here.
The workaround worked for some weeks, but now another error is back.

**Comment by adn77** [comment]
I just uploaded a hopefully fixed version that uses the new API.

**Comment by Lxtxs** [comment]
It works perfectly. Thanks

**Comment by DunkanA** [comment]
> I just uploaded a hopefully fixed version that uses the new API.

Thank you :-)

**Comment by ralmulle** [comment]
Is the answer to the request faster now?

**Comment by adn77** [comment]
> Is the answer to the request faster now?

That's rather up to Amazon ;)

**Comment by Matthy1810** [comment]
> Is the answer to the request faster now?

For me it is as fast as before. I don't experience a delay.

**Comment by Lxtxs** [comment]
Hello again, thanks for the fix. Things are working for me the same as before. It runs very fast.
