### ISSUE TITLE
Double logon required

### ISSUE THREAD

**Issue by jamesw4** [thorsten-gehrig/alexa-remote-control#18]
Script recently stopped working for me. I suspected captcha so tried manually logging in with javascript disabled. When it's disabled I can NEVER logon first time. First logon always results in "Enter a valid e-mail or mobile number" re-entering password second time results in successful login. Similar sort of amazon auth issue reported here https://github.com/speric/kindle-highlights/issues/11

Is it possible to modify script to auto retry?

**Comment by adn77** [comment]
The script actually sends the login form empty at first and as a second try submits user name and password.
If the login does not work for you it's most likely a different user agent or accept language... Try the settings you see in your browser's request header.
Alex

**Comment by Apollon77** [comment]
I also had this effect but only in browser ! The script never showed this effect.
