### ISSUE TITLE
Commands not working

### ISSUE THREAD

**Issue by yomakaineru** [thorsten-gehrig/alexa-remote-control#181]
I am trying to run this from Mac, but none of the options for sending commands to Alexa are working.
I have confirmed that the necessary components are in place and that the -a option functions correctly. 

Are there any solutions?

**Comment by adn77** [comment]
Some of the commands used have different options on BSD 😞 

One candidate was the date command. E.g. check what *date +%s* produces.

If you are trying the -a option, it's likely that the login already fails. Check which files /tmp/.alexa.* have already been created.

**Comment by yomakaineru** [comment]
The reason it didn't work was that I hadn't created an Amazon account itself and was only logged in with an Amazon developer account. Thanks!!!!
