### ISSUE TITLE
Volume info

### ISSUE THREAD

**Issue by FWillems** [thorsten-gehrig/alexa-remote-control#19]
Hi,
thank you for the nice script, it's working perfectly. Is it possible to get the actual volume from a device back as an info? Perhaps like actual volume is set to level 5 or to 50%.

**Comment by adn77** [comment]
I believe the output of "-q" contains the volume in pecentage. If nothing is currently playing then the volume reading will disappear though.
E.g: alexa_remote_control.sh -d Bad -q | grep -m 1 '"volume": [0-9]'

**Comment by FWillems** [comment]
Thank you. That works fine!

`alexa_remote_control.sh -d Bad -q | grep  '"volume": [0-9]' | awk {'print $2'}`
