### ISSUE TITLE
Support for amazon.com.au

### ISSUE THREAD

**Issue by idkpmiller** [thorsten-gehrig/alexa-remote-control#20]
Hi there I have been having a play with the script and different settings, here is a list of my changes and the outcomes.

I can login successfully with the following:

| LANGUAGE |      AMAZON        |    COMMENT                                                                                    |
|===============================================================|
| de-DE          |  amazon.de         | ERROR possibly get a capcha login screen.
| de-DE          | amazon.com.au   | Cookie expired,,, Login failed Aborting.
| en-GB          | amazon.co.uk     |  ERROR possibly get a capcha login screen.
| en-US          | amazon.com       |  ERROR possibly get a capcha login screen. 
| en-NZ         | amazon.com.au   | Cookie expired,,, Login failed Aborting.
| en-NZ         | amazon.de          | Cookie expired,,, Login failed Aborting.
| en-AU         | amazon.com.au   | Cookie expired,,, Login failed Aborting.
| en-AU         |  amazon.de         | ERROR possibly get a capcha login screen.
|_______________________________________________________________________________________________________| 

Whenever I try to connect to com.au I always get the same error shown in detail below. I do NOT get the capcha error unless I am redirecting to a non native site.

./alexa_remote_control.sh
cookie does not exist. logging in ...
cookie expired, logging in again ...
log in failed, aborting

in order to get past the Capcha ERROR, I can disable javascript and clear the cache on a browser, heade to the http URL of the remote regional site and login it will ask for a capcha and once that is successfully completed I am redirected to the native site (com.au) where I can then enter my username password combination and get logginged into the web app.
Once I have done this is a rerun the script I see this message.

 ./alexa_remote_control.sh
cookie does not exist. logging in ...
device list does not exist. downloading ...
no alexa command received

I however have had no luck when setting the AMAZON variable to amazon.com.au; I think there is some issue with the script in the redirect case that is preventing it functioning.

Regards

Paul

**Comment by adn77** [comment]
Sorry, I do not fully understand
  no alexa command received

only means that you have to add an option like "-a" to the command.
The last output actually looks fine.

**Comment by idkpmiller** [comment]
in simple terms the applications fails to work with 'amazon.com.au' hub.
I have gone down a different path so not a problem for me any more, up to you if you fix it.
Thanks

Paul

**Comment by hoodlumj3** [comment]
Seems to be working fine for me - followed instructions on https://github.com/586837r/node-red-contrib-alexa-remote2/blob/master/get_cookie.md using alexa.amazon.com.au played with examples 100% working - very happy!! TYSM!

**Comment by hoodlumj3** [comment]
use https://github.com/586837r/node-red-contrib-alexa-remote2/ works great using alexa.amazon.com.au,  played with the examples 100% working - very happy!!

**Comment by idkpmiller** [comment]
Glad it works for you Matt, it is quite possible the reason for it not working was not the AU hub but something else, it does not matter as there has been no interest to diagnose the root cause andf Ias I said previously I have moved on to a solution that works great for me.
I recommend the ticket is closed.

Thanks

Paul

**Comment by hoodlumj3** [comment]
To further test I grabbed the cookie that I was using for remote2 and stuffed it in this remote and that worked too.
Can I ask what you’ve alternatively found ? I like to keep my options open. ;)
