### ISSUE TITLE
Not working with Echo Dot 3rd Gen.

### ISSUE THREAD

**Issue by rafdalb** [thorsten-gehrig/alexa-remote-control#22]
Looks like it doesn't work with the new Echo Dot 3rd Gen.?

I've both a 3rd Gen. and 2ng Gen. dot at home, both apparently configured same way.

Same speak command works on 2nd Gen, it doesn't on 3rd Gen.

**Comment by Apollon77** [comment]
What exactly ist he result? Can you create a routine with speak output and trigger that?

**Comment by rdalbenzio** [comment]
You're right, even an Alexa routine doesn't work on 3rd Gen, while it's working on 2nd Gen (I've both an Eco Dot, and Echo. 

I'll check with Amazon.

I think you can close the issue.

Sorry for bothering,
Raf.

**Comment by Apollon77** [comment]
Leave it open (from my side) and please report back on the solution you found.

**Comment by rdalbenzio** [comment]
Thanks,

I would ask if someone else had a similar issue. 

I tried with an Echo Spot and it also works. Tried to send a feedback email to Alexa with no answer so far:

In summary:

1)	Echo Dot (2nd Gen) Works
2)	Echo (2nd Gen) Works
3)	Echo Spot works
4)	Echo Dot (3rd gen) doesn’t work.

Raf.

**Comment by rdalbenzio** [comment]
I don't know what happened, I switched off my dot, I switched on again, change the language to Italian and then back to English and Suddenly it started working. 

I'm sorry for not having an answer on why it started (firmware upgrade? But there is no log in history settings)

**Comment by Apollon77** [comment]
@spady7 It would be very helpful to know what exactly you called and what was planned to happen
