### ISSUE TITLE
Loop command

### ISSUE THREAD

**Issue by martialman** [thorsten-gehrig/alexa-remote-control#26]
Hello,
Tank you for your script it work perfectly on echo dot 3.
A simply question, it's possible to have the "loop" command?
I have tried to add line in the script remote_control_plain but no work with an error : 
In the script : 
	shuffle)
			COMMAND='{"type":"ShuffleCommand","shuffle":"true"}'
			;;
          loop)
			 COMMAND='{"type":"LoopCommand","loop":"true"}'
	    	       ;;
In console : 
~ $ sudo /home/pi/domoticz/alexa_remote_control_plain.sh -d "Martial - Echo Dot" -s d4aa4219-78e2-49d9-8f55-e6d686c30a77:1 -e loop
sending cmd:{"type":"LoopCommand","loop":"true"} to dev:Martial_-_Echo_Dot type:A36DOYMUN6DTXA serial:G090U60788740S7B customerid:A2LFOBGMAQ91H0
{"message":"Invalid command specified"}

Tank you

**Comment by adn77** [comment]
@martialman I will upload a new version tonight which includes a "repeat" command. Thanks for the suggestion!

The loop command is actually 
`{"type":"RepeatCommand","repeat":true}`
