### ISSUE TITLE
Device owner problem with a household of Echos

### ISSUE THREAD

**Issue by swbradshaw** [thorsten-gehrig/alexa-remote-control#27]
Background: I have 4 Amazon Echos in the house. 2 of them were originally activated by me, 2 of them were activated by my wife.  All 4 of them are shown in my Amazon account, and my wife's account.  When we are at a given device we can say "Alexa, switch accounts".  This way my wife can play her music and I can play mine.

Problem: This script will successfully pull all 4 devices and show them, however, I can't control the ones originally activated by my wife. The reason is because this script is making the web request with my wife's deviceOwnerCustomerId (reported by Amazon as the owner), but I'm signed in as myself (a different deviceOwnerCustomerId). If I change the code to always use the deviceOwnerCustomerId of myself (hardcode) the script works fine.

Solution: I believe the fix for this is this component should access https://alexa.amazon.com/api/bootstrap and pull the deviceOwnerCustomerId of the current user. It would only need to do this one time (perhaps after it stores the cookies). It should then use this deviceOwnerCustomerId to make the calls, and not try to make the calls for another user that is not signed in.  At the very least, perhaps a config option can be setup so that you can override the deviceOwnerCustomerId for all the calls.

I understand this code was copied from another library - I actually contacted the author of that plugin as well.

**Comment by adn77** [comment]
Hi @swbradshaw 
I actually call the /api/bootstrap endpoint to determine if the cookie is still valid.
A long time ago I even used the customerId that is returned there (currently I don't parse the reply for the customerId). I retrieve the customerId from the device list as it is easier to parse the JSON with the "plain" version only once.

Thanks for the input - will fix this!

Alex
