### ISSUE TITLE
Getting lists

### ISSUE THREAD

**Issue by bobMuk** [thorsten-gehrig/alexa-remote-control#32]
Is there any way you can retrieve your shopping list using the script?
The data is there at https://alexa.amazon.co.uk/spa/index.html#lists/namedLists
I've tried tinkering with the script but can't find a way to GET anything.  Think it's possible?

**Comment by adn77** [comment]
@bobMuk  generally I suggest starting with the show_queue() function (-q option).
Just copy+paste one of the cURL commands.

For lists, you will want to query
/api/namedLists (shopping + to-do list)
/api/lists/linkedPartners (no idea)
/api/lists/fetchUserPreference
/api/namedLists/<ListID>/items (actual content of a list)

Alex

**Comment by bobMuk** [comment]
Thanks.  After I posted the question I did some googling of the API and stopped generally being lazy... though I am still too lazy to "officially" contribute to the project.
But if anyone wants it, I've created list functions: 
-listlist
-getlist <listname>

Here's a diff of my changes against v0.10b of the script:


diff alexa_remote_control.sh.old alexa_remote_control.sh
101a102,103
> GETLIST=""
> LISTLIST=""
263a266,273
>               -getlist)
>                       GETLIST="true"
>                       RETRIEVELIST=$2
>                       shift
>                       ;;
>               -listlist)
>                       LISTLIST="true"
>                       ;;
747a758,786
> # list functions
> #
> list_list ()
> {
> ${CURL} ${OPTS} -s -b ${COOKIE} -A "Mozilla/5.0" -H "DNT: 1" -H "Connection: keep-alive" -L\
>  -H "Content-Type: application/json; charset=UTF-8" -H "Referer: https://alexa.${AMAZON}/spa/index.html" -H "Origin: https://alexa.${AMAZON}"\
>  -H "csrf: $(awk "\$0 ~/.${AMAZON}.*csrf[ \\s\\t]+/ {print \$7}" ${COOKIE})" -X GET \
> "https://${ALEXA}/api/namedLists" | jq '.lists[] |  .type' | sed -e 's/"//g'
> }
>
>
> get_list ()
> {
> #first get list ID from supplied name
> mylistid=$(${CURL} ${OPTS} -s -b ${COOKIE} -A "Mozilla/5.0" -H "DNT: 1" -H "Connection: keep-alive" -L  -H "Content-Type: application/json; charset=UTF-8" -H "Referer: https://alexa.${AMAZON}/spa/index.html" -H "Origin: https://alexa.${AMAZON}"  -H "csrf: $(awk "\$0 ~/.${AMAZON}.*csrf[ \\s\\t]+/ {print \$7}" ${COOKIE})" -X GET "https://${ALEXA}/api/namedLists" | jq '.lists[] | select(.type == "'$RETRIEVELIST'") | .itemId' | sed -e 's/"//g')
> if [ -z $mylistid ]
> then
>         echo "Could not identify list $RETRIEVELIST"
>         return 1
> fi
>
> #get list contents
> ${CURL} ${OPTS} -s -b ${COOKIE} -A "Mozilla/5.0" -H "DNT: 1" -H "Connection: keep-alive" -L\
>  -H "Content-Type: application/json; charset=UTF-8" -H "Referer: https://alexa.${AMAZON}/spa/index.html" -H "Origin: https://alexa.${AMAZON}"\
>  -H "csrf: $(awk "\$0 ~/.${AMAZON}.*csrf[ \\s\\t]+/ {print \$7}" ${COOKIE})" -X GET \
> "https://${ALEXA}/api/namedLists/$mylistid/items" | jq '.list[] | select(.completed ==  false) | .value' | sed -e 's/"//g'
> }
>
> #
760c799
< if [ -z "$LASTALEXA" -a -z "$BLUETOOTH" -a -z "$LEMUR" -a -z "$PLIST" -a -z "$HIST" -a -z "$SEEDID" -a -z "$ASIN" -a -z "$PRIME" -a -z "$TYPE" -a -z "$QUEUE" -a -z "$LIST" -a -z "$COMMAND" -a -z "$STATIONID" -a -z "$SONG" -a -n "$LOGOFF" ] ; then
---
> if [ -z "$LISTLIST" -a -z "$GETLIST" -a -z "$LASTALEXA" -a -z "$BLUETOOTH" -a -z "$LEMUR" -a -z "$PLIST" -a -z "$HIST" -a -z "$SEEDID" -a -z "$ASIN" -a -z "$PRIME" -a -z "$TYPE" -a -z "$QUEUE" -a -z "$LIST" -a -z "$COMMAND" -a -z "$STATIONID" -a -z "$SONG" -a -n "$LOGOFF" ] ; then
889a929,932
> elif [ -n "$GETLIST" ] ; then
>       get_list
> elif [ -n "$LISTLIST" ] ; then
>       list_list
