### ISSUE TITLE
Last Alexa does not account for multiple Echos hearing the command

### ISSUE THREAD

**Issue by alandtse** [thorsten-gehrig/alexa-remote-control#38]
Hi,
I actually don't use the script, but help maintain a python version for Home Assistant that was based off this script. 

While implementing lastAlexa functionality for ourselves, we ran into an issue where if a user had multiple Alexa devices that heard the event, it's possible that relying on the last activity record wouldn't work because it the `activityStatus` was a `DISCARDED_NON_DEVICE_DIRECTED_INTENT` instead of a `SUCCESS`. This apparently happens if multiple devices have to decide which one needs to respond to the same command.  I [coded a solution](https://gitlab.com/alandtse/alexapy/blob/master/alexapy/alexaapi.py#L217) that pulls 10 records from the API and does a for loop until it find a success.  I thought I'd report it to you since you would have the same bug we ran into. While I'd normally provide a pull request, I've been too lazy to set up the script to test and debug it but hopefully I've provided enough info so you can implement a fix easily.

**Comment by adn77** [comment]
@alandtse thanks for the feedback! I added the check as well
