### ISSUE TITLE
runing only once

### ISSUE THREAD

**Issue by mister-extra** [thorsten-gehrig/alexa-remote-control#4]
hi - using it on raspberry 👍 

it works for three times and then this message appears:

sending cmd:{"type":"PlayCommand"} to dev:Echobad type:A3Sxxxx2HxxYF serial:G0xxxxxxx1860WED
{"message":"No routes found","userFacingMessage":null}

command was: "alexa_remote_control_plain.sh -d Echobad -e play"
on the alexa-amazon-website : the Echobad Device is showing that it is not connected - after 5 minutes it works again (sometimes) and I can also use your script ! the script is doing something strange with the echo.dot device

any ideas

**Comment by adn77** [comment]
Hi @mister-extra ,
this usually happens when there is no context for the command received.
E.g. there's no queue for the play command to be played.
I also receive this quite often on Echos which have been inactive for a while and I try to set the volume before playing anything.

All you can do is to provide more context (use one of -r/-s/-t/-v/-w) and start over again.

**Comment by mister-extra** [comment]
I'm sorry - that I write after closing the issue - I have tried the new version and have the same problem.
 e.g. I have used it 3 hours ago and it worked. Now I have tried it again and the tunein sender is not starting . I have to go into the alexa app and start the tunein sender and stop it. after this I can use the script. I do not have a problem with the speak, vol command or with bluetooth. do you have any idea. 

this is the command I use:  alexa_remote_control_plain.sh -d Echozimmer -e play -r s25217

**Comment by adn77** [comment]
the command is wrong, just use:

alexa_remote_control_plain.sh -d Echozimmer -r s25217

**Comment by mister-extra** [comment]
thanx for your fast answer  -  I will change this and see what happens tomorrow morning
the speak option is perfect - I was looking for something like this for a long time - thx for this!
