### ISSUE TITLE
TTS loses full stops.

### ISSUE THREAD

**Issue by dpembo** [thorsten-gehrig/alexa-remote-control#42]
Due to the sed regular expression, full stops are missing out of anything you send to TTS which means whatever Alexa says comes out in one full sentence 😃. 

Can be resolved by adding the full stop into the expression (\.) like the below.
Doesn't seem to cause any issues when I've tried it and puts in suitable pauses in the TTS.

```
SEQUENCECMD='Alexa.Speak'
TTS=$(echo ${COMMAND##*:} | sed -r 's/[^-a-zA-Z0-9_,?!\. ]//g')
TTS=",\\\"textToSpeak\\\":\\\"${TTS}\\\""
```

Could probably do similar for semi-colon ';' but I've not tested this.  Before the change the only way to stop her mid flow was to use a hyphen '-'.

**Comment by adn77** [comment]
Thanks for pointing that out.
I actually removed all replacements except for those required by the JSON formatting.

Since I now use a tempfile for the POST data, there's no need to escape much more :)
