### ISSUE TITLE
Set volume to devices with no more actions

### ISSUE THREAD

**Issue by orxaz** [thorsten-gehrig/alexa-remote-control#49]
Hi.

Would be nice to be able to set the device's volume not only to play or say something, e.g. at night, set volume of all devices to 30%, and at morning set them at 80%.

Is it possible to do it now? I have been trying with no success.

Thanks! Good job!

**Comment by adn77** [comment]
This can be done by creating a Routine/Automation. Create one that sets the volume to 30% and one that sets the volume to 80%. Then just call them in the script -e automation:night

**Comment by orxaz** [comment]
Thanks @adn77 

Is not the best solution, but seems to be the unique to do that I want.

For the Echo's side, would be nice to be able to create a routine that changes the volume of all echo devices, but I must do one for each device.

Anyway, many thanks for your reply.

**Comment by adn77** [comment]
It's not very hard to add a volume setting before and after the speak command - it only requires the proper escaping of the (VERY LONG) JSON sequence. That's why I haven't done it yet, but it is a planned feature!

**Comment by orxaz** [comment]
I've tried this, thinking that was already implemented, but obviusly did not get it to work.

Do you think/know that will this kind of command leave the volume level adjusted, to later play music, for example?

**Comment by adn77** [comment]
@orxaz  please check the latest version, it includes the volume setting for the speak command as well as an alternate method for setting the volume.
To do it on all echos, use the special "ALL" device

**Comment by orxaz** [comment]
Thanks @adn77 , now I can adjust all the echo's volume from crontab!
