### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by jamesw4** [thorsten-gehrig/alexa-remote-control#5]
Seems to have recently stopped working for me. Can't even get the list of my devices. Suspect amazon have changed something?

**Comment by ManuelW77** [comment]
I have a similar problem, i found only 2 of my 3 devices. A few weeks ago it found all 3 devices.

**Comment by axwax** [comment]
updating the script to the latest version at https://loetzimmer.de/patches/alexa_remote_control.sh has done the trick for me...

**Comment by adn77** [comment]
I am pushing my changes to Thorsten's repository. You should be able to use the code from here as well.
