### ISSUE TITLE
Implement Alexa.Music.PlaySearchPhrase

### ISSUE THREAD

**Issue by tricoos** [thorsten-gehrig/alexa-remote-control#51]
Can you please support Alexa.Music.PlaySearchPhrase? I found it on https://github.com/keatontaylor/alexa_media_player (where I also found the other commands I recently implemented).
I do not have the required shell scripting capabilities otherwise I would also have implemented it.

The thing is: if you are an Amazon Music Unlimited subscriber as I am you can simply play any song which is available within that subscription. However, these songs are neither imported nor purchased so I cannot use any of the existing methods implemented.

**Comment by adn77** [comment]
@tricoos please check the latest release for this feature.
you should be able to use something like `-e playmusic:AMAZON_MUSIC:'whatever you want to listen to'`
Note: this doesn't work properly on multi-room devices...
