### ISSUE TITLE
Add compatibility for macOS

### ISSUE THREAD

**Issue by mkozjak** [thorsten-gehrig/alexa-remote-control#54]
Currently the script fails with `sed: illegal option -- r`.
macOS uses BSD tools, hence the options are somewhat different.

**Comment by adn77** [comment]
Sorry, you may have to replace '-r' with '-E'.
Changing it in the code is too big a regression...

**Comment by mkozjak** [comment]
Tried and there were some more issues. I guess it's a hassle.

**Comment by mkozjak** [comment]
@adn77 : there's no proper api to control alexa?

**Comment by adn77** [comment]
If there was, this script wouldn't exist ;-)
No, unfortunatly there is not.

**Comment by walthowd** [comment]
@mkozjak You can see how we handled it here:

https://github.com/walthowd/ha-alexa-tts

**Comment by mkozjak** [comment]
Thanks!
