### ISSUE TITLE
alexa_remote_control.sh returned: 256

### ISSUE THREAD

**Issue by Philtass** [thorsten-gehrig/alexa-remote-control#55]
Hello. This script usually works well and I use it to make alexa do and say a lot of thing. Now I have this return code 256. What does it mean ?

**Comment by adn77** [comment]
The script doesn't use exit codes besides "0" and "1".
Which variant are you using and which version?

Do you call the script directly or via another script?

**Comment by Philtass** [comment]
Hello, thanks for answering. 
I just use this script as it is recommended and did not alter it. But relax now,I found the trick: I forgot to change IP of alexa in the setting part of the script as I changed my wifi router.
It's working now.
I really don't know why return code is 256 but it's surely because of a wrong IP adress.
Thanks again for helping.
--
Envoyé depuis l'application myMail pour Android vendredi, 28 juin 2019, 11:19PM +02:00 de Alex  notifications@github.com :
