### ISSUE TITLE
-e vol no work

### ISSUE THREAD

**Issue by Hydci** [thorsten-gehrig/alexa-remote-control#58]
Hello,

I have a problem the command -e vol no work on the other hand the order -e speack work
the order -e vol is no longer available?
script version 2019-06-28 alexa_remote_control.sh

`sudo ./alexa.sh -d Salon -e vol:50
sending cmd:{"type":"VolumeLevelCommand","volumeLevel":50} to dev:Salon type:XXXXXXX serial:XXXXXXXX customerid:XXXXXXXX
{"message":"No routes found","userFacingMessage":null}
`

**Comment by adn77** [comment]
This happens when there is no audio playing on that particular device.
Try creating a routine that sets the volume. Then call the routine from alexa.sh

**Comment by adn77** [comment]
@Hydci  please check the latest version, I included an alternate method for the volume setting which does just what I described to you ;)
