### ISSUE TITLE
ADD volume set up for option -e speak:''

### ISSUE THREAD

**Issue by BedoM** [thorsten-gehrig/alexa-remote-control#62]
Hello your script is very very good !

can y add volume set up for option -e speak:'YOUR TEXT' ?

thank'youuuuu

**Comment by adn77** [comment]
Which volume would you expect the script to restore after the speak is done?

**Comment by BedoM** [comment]
I would set up the volume for -e speak:'Hello' ?

**Comment by adn77** [comment]
Please check the latest version. you can preset the SET_SPEAKVOL or give an environment variable of SPEAKVOL each time you run.
