### ISSUE TITLE
Alexa doesnt do anything after executing a command.

### ISSUE THREAD

**Issue by DerMatteo** [thorsten-gehrig/alexa-remote-control#63]
I executed some commands. Output: 

> root@SmartHomeV2:/var/homebridge/devices/sprachausgabe# ./alexa_remote_control.sh -e automation:'aufwachen'

setting default device to:
MatteosZimmer
sending cmd:automation:aufwachen to dev:MatteosZimmer type:++++++++++++++++ serial:++++++++++++++ customerid:++++++++++++++++
<
But alexa doesnt do anything. The config file seems correct.

**Comment by DerMatteo** [comment]
#

**Comment by adn77** [comment]
Do other commands like play/pause/speak wotrk?

Could you please check whether the cookie file (/tmp/.alexa.cookie) does contain a "csrf" cookie.
In rare cases, deleting the cookie was necessary.

Alex

**Comment by DerMatteo** [comment]
The Play/Pause and Speak dont work either.

I will check the csrf cookie now

**Comment by DerMatteo** [comment]
Yes there is a csrf cookie, im gonna delete it now

**Comment by adn77** [comment]
Delete the entire file, and login again

**Comment by DerMatteo** [comment]
I dont know how to login. I logged in with chrome, and with cookietext-export i pasted this in the file. Do i have to open firefox on my pi, disable java script and log in?

**Comment by adn77** [comment]
The script is supposed to do the login for you. Do you use MFA on your Amazon account?

**Comment by DerMatteo** [comment]
No. I dont use MFA.

**Comment by adn77** [comment]
Setting the environment variables EMAIL and PASSWORD and running the latest unmodified version should log you in.

**Comment by adn77** [comment]
Works with 90% of German Amazon accounts

**Comment by DerMatteo** [comment]
That worked. Executed the script without any changes and it worked. Maybe because i pasted the cookie. But it didnt log in

**Comment by adn77** [comment]
yes

**Comment by DerMatteo** [comment]
Also hätte ich mir die mühe mit dem Englisch garnicht machen müssen :D Auf jeden Fall danke nochmal. Mit Leuten, die einem helfen können direkt zu schreiben ist nochmal viel besser als sich Lösungen im Internet zu suchen. Danke

**Comment by adn77** [comment]
Du brauchst eigentlich kein Cookie zu kopieren. Email und Passwort sollten ausreichen. Der Cookie läuft irgendwann ab
.

**Comment by DerMatteo** [comment]
Ok. Danke :D Ich werde dieses Problem werde ich jetzt schließen.
