### ISSUE TITLE
"Alexa Show 5" Webcam Video Access Feature 

### ISSUE THREAD

**Issue by dev-segal** [thorsten-gehrig/alexa-remote-control#65]
So, I've been using this script for about a week now and it's been absolutely amazing. It's been incredibly fun and helpful, and I can't wait to see what I'll do next with it. 

_That's where this issue comes in: I was wondering if there's currently any capability that supports accessing the "alexa show 5" video webcam. I know you're able to use the drop in feature but I'd love to know if there's a more functional version implemented in this script._

If not, are you aware if it's a possible feature to be implemented later down the road? 

Thanks, - Joshua.

**Comment by adn77** [comment]
I really doubt there ever will be a chance of accessing the video. Your best bet is going to be a Skill that can access the cam combined with a routine that can be triggered to operate that Skill.
