### ISSUE TITLE
More sequence commands

### ISSUE THREAD

**Issue by michaelsage** [thorsten-gehrig/alexa-remote-control#69]
Hi,
This is such a great little script. Thank you!
I am using it to trigger automations at the moment. I would like to have the ability to trigger individual home automation devices? I couldn't really see anything in Alexa's API, but if you point me in the right direction I can have a go at extending the code :)

**Comment by adn77** [comment]
Sorry for the late reply,
unfortunately there isn't anything exposed in regards to home automation.

Actually alexa-remote-control is intended to be used by existing Home Automation software...

**Comment by michaelsage** [comment]
No worries. I am using routines within Alexa and the alexa remote control script is running them fine. Thanks for the response! :)
