### ISSUE TITLE
Routine Limit´s?

### ISSUE THREAD

**Issue by Dizzy1985** [thorsten-gehrig/alexa-remote-control#70]
Hallo. 
Ich habe ein Problem mit dem Script beim ausführen von Routinen. 
Wenn ich mehr als 20 Routinen in der Alexa-App (ganz einfach und nur mit einem einfachen Wort gekennzeichnet) anlege, werden die neuen Routinen als nicht vorhanden ausgegeben.
ERROR: no such utterance 'Fenster' in Alexa routines
Alles was über den älteren vorhanden Routinen angelegt wird, wird nicht ausgeführt, bzw. wird zwar ausgeführt, aber dafür eine ältere nicht mehr. Ist das Script irgendwie auf ein Limit gesetzt, oder wie bekomme ich es hin das dass Script nach neuen Routinen sucht und diese auch ausführt, mit dazu nimmt?

Hi.
I have a problem with the script when executing routines. If I create more than 20 routines in the Alexa app (quite simply and with just a single word), the routines will be displayed as missing.
ERROR: No search utterance 'window' in Alexa routines
Everything that is created over the older existing routines, is not executed, or is executed, but no longer an older one. Is the script somehow set to a limit, or how can I get it that script searches for new routines and executes them, takes with it?

**Comment by Apollon77** [comment]
When reading routines the default limit is 20 ... can be increased via url parameter

**Comment by adn77** [comment]
This is due to pagination, I am going to update this as soon as I find time.

**Comment by adn77** [comment]
I created a new version with the limit being 200 automations

**Comment by Dizzy1985** [comment]
Funktioniert 👍
