### ISSUE TITLE
Play song through default music service

### ISSUE THREAD

**Issue by Grynr38** [thorsten-gehrig/alexa-remote-control#78]
Hi,
Would it be possible to use the default music service defined in Alexa's App (Deezer in my case) to play songs/playlist/... on any device using the Alexa-Remote-Control ?

I've got the script up and running in no time, it is quite great actually. I am just trying to make a deezer companion app since the skill for alexa is terrible.

Any support would be greatly appreciated.
Thank you and have nice 2020 !

**Comment by Grynr38** [comment]
I would also like to be able to make Alexa sing a specific song in the spirit of :
./alexa.sh -e singasong:"happybirthday" (for example...)

Thanks !

**Comment by adn77** [comment]
Hi @Grynr38,

I haven't seen any mention of Deezer in the Alexa Webfrontend. Hence, I don't know how to trigger that service :( Sorry!

Alex

**Comment by Grynr38** [comment]
Hi Alex,
Thank you very much for your quick reply. I really enjoy using the script you made, if there is any way I could help you, please do not hesitate contacting me.

Thanks again,
G.

**Comment by adn77** [comment]
You can always play around with the alexa.amazon.com web interface and look at the requests made.
If you find out any request that controls other music services, let me know and I will include that in the script.
