### ISSUE TITLE
Nice to have: --version

### ISSUE THREAD

**Issue by christianTF** [thorsten-gehrig/alexa-remote-control#81]
Possibly you could add a `--version` parameter that states the version line that is listed in the top comments.
For me this would be useful to get the version for a logfile executing your script.

Nothing urgent, but if you can't sleep tonight... :stuck_out_tongue_closed_eyes:

Thanks, Christian

**Comment by adn77** [comment]
I added the `--version`.

Alex

**Comment by christianTF** [comment]
Works like a charme! 

Thanks Alex!

![image](https://user-images.githubusercontent.com/14220265/72757848-58aa9780-3bd1-11ea-9c78-d965d11b89bd.png)
