### ISSUE TITLE
Question: Is MFA used?

### ISSUE THREAD

**Issue by christianTF** [thorsten-gehrig/alexa-remote-control#83]
Hello Alex,

on logon process requesting the cookie: Does the script show anything different if using MFA?
I've enabled MFA at Amazon, and inserted oathtool generated key at Amazon.
I set `export OATHTOOL=oathtool` and `export MFA_SECRET="AAAA BBBB ...."`, as well as `EMAIL` and `PASSWORD`.

I'm not sure if I was logged on using MFA or by the normal email/password process.

```
loxberry@loxberry-dev:~/webfrontend/htmlauth/plugins/alexa2lox $ ./alexa_remote_control.sh -a
cookie does not exist. logging in ...
device list does not exist. downloading ...
the following devices exist in your account:
```

Unfortunately, MFA now is also used for normal amazon.de web access. It's annoying that Amazon doesn't offer a service token.

lg, Christian

**Comment by adn77** [comment]
Not sure I follow...

If you provide an MFA secret then MFA will be used. There is no different output for MFA logins.

Alex

**Comment by christianTF** [comment]
That’s the point. I wasn’t sure, if I should see some different output with MFA.
