### ISSUE TITLE
Speak on multiroom group not supported?

### ISSUE THREAD

**Issue by sammyke007** [thorsten-gehrig/alexa-remote-control#85]
Hi

I have a multiroom group called "Down".

**bash alexa_remote_control.sh -d Down -e speak:'test'** results in "Unsupported command". Is there a possibility to announce TTS on more devices than 1?
**bash alexa_remote_control.sh -d ALL -e speak:'test'** works, but goes through each device and each multiroom group... The fact that it runs on the multiroom group with ALL shows that it's possible.

Sammy

**Comment by adn77** [comment]
There is two things to this:
1. I created the special *ALL* device for actions iterating over all devices.
1. The TTS/speak routine does not support multi-room devices (try for yourself in the Alexa App). When running a TTS command to the *ALL* device it will also skip multi-room devices for that very reason

All you can do for now is calling consecutively **alexa_remote_control.sh** with each of the device in your *Down* group.

**Comment by sammyke007** [comment]
Ok Alex, tnx for the quick answer!

**Comment by jqnatividad** [comment]
@sammyke007 just wanted to let you if you set USE_ANNOUNCEMENTS_FOR_SPEAK to 1, you can use multiroom groups for speak.

In my case, I had the built in group ‘Everywhere’ which broadcasts to all 5 Alexas in the house simultaneously, e.g.

bash alexa_remote_control.sh -d Everywhere -e speak:”test”

I also had the groups “Living area” (Living room and Kitchen) and “Sleeping area” (all the bedrooms), and I can use those groups as well.

cc @adn77
