### ISSUE TITLE
Speak message volume issue

### ISSUE THREAD

**Issue by harrier914** [thorsten-gehrig/alexa-remote-control#87]
Hi, your script is amazing! 

A little issue from me: after the script (ver. 0.15c) speak out a message in echo dot, it always set back to very low volume (white light strip display). SET_SPEAKVOL="0" (untouched) has been set in the script, any other parameter is missing in my setting? I am using Echo 3rd gen. Thanks.

**Comment by adn77** [comment]
Hmm, and I suppose there is no ENV var that would override $SPEAKVOL?

If you see the white light strip light up after the message, then the script is  executing the speak command with volume settings. This is governed by the ìf` condition on line 629:
`if [ -n "${TTS}" -a $SPEAKVOL -gt 0 ] ; then`

So it looks like your $SPEAKVOL is evaluated to something bigger than 0.
There is two things you can try:

1. make sure $SPEAKVOL is really `0` => insert an `echo "SpeakVol=${SPEAKVOL}"` in line 628
1. see if it's a casting problem (from String to Integer) => change line 629 to
`if [ -n "${TTS}" -a $SPEAKVOL -gt 0 -a "${SPEAKVOL}" != "0" ] ; then`

**Comment by harrier914** [comment]
Hi, I don't think therer is ENV setting override $SPEAKVOL. 

Try your suggestions as above. The echo message display:

pi@raspberrypi:~ $ ./alexa_remote_control_plain.sh -e vol:100 -e speak:"Hello!"
setting default device to:
Dining_Echo_Dot
sending cmd:speak:Hello! to dev:Dining_Echo_Dot type:A1RABVCI4QCIKC serial:G090XG07935314N2 customerid:A3D5W7XCJ1I41D
SpeakVol=0

Also putting the '-e vol:100' in the input argument still speak very low volume output. I am using your "plain" version as no 'jq' installed in my RPi. 

Will there be difference between "plain" and "non-plain" script version for speak volume? 
Thanks.

**Comment by adn77** [comment]
You cannot have two `-e` commands at the same time.

Try running:
`/alexa_remote_control_plain.sh -e vol:100`
`SPEAKVOL=0 /alexa_remote_control_plain.sh -e speak:hello`

**Comment by harrier914** [comment]
Hi, it work perfect with your suggested commands under RPi.  But it is still happening when run the script using "Node-Red exec node". I suspect incorrect echo speak volume may relate to node-red exec node not this script. Thanks.

**Comment by harrier914** [comment]
Hi, the problem is resolved after reinstalled and configured the script files again in RPi. It works perfectly in both sh cmd and nod-red exec node now! Thanks.
