### ISSUE TITLE
Support SSML markup in Text To Speech

### ISSUE THREAD

**Issue by jqnatividad** [thorsten-gehrig/alexa-remote-control#88]
It'd be awesome if SSML support is added

https://developer.amazon.com/en-US/docs/alexa/custom-skills/speech-synthesis-markup-language-ssml-reference.html

**Comment by adn77** [comment]
I know it can be done, as ioBroker and openHAB already have it for a long time.

Just didn't get around to construct a proper test SSML ;)
Will have a look at it tonight.

**Comment by adn77** [comment]
You will have to enable the Announcement feature for each Echo device and then set `USE_ANNOUNCEMENT_FOR_SPEAK` to `1`

**Comment by jqnatividad** [comment]
Amazing! Works like a charm!  Any chance you can also include support for the Alexa Skills Sound Library?

https://developer.amazon.com/en-US/docs/alexa/custom-skills/ask-soundlibrary.html

**Comment by adn77** [comment]
Please note that you can only use very few of the sound bits in the skill library.
Unfortunately that's trial and error finding one.

I tried the Trumpet - the forth entry finally worked.

**Comment by jqnatividad** [comment]
Thanks for the quick turnaround!

I was hoping I can just use the sound library SSML inside speak, but this is also good.  For example:

`alexa_remote_control.sh -d Everywhere -e speak:”<audio src=‘soundbank://soundlibrary/home/amzn_sfx_doorbell_chime_01’/> There is someone at the door!”
`
FYI, as embedded SSML, I double checked and can confirm that the entire library works using the Alexa Developer Console.

With the current sound implementation as you pointed out, its hit and miss...

**Comment by adn77** [comment]
Just in case somebody else is reading this... ;)

You cannot use the soundlibrary in `-e speak` (even if it supports SSML now!
The sound library that seems to be implemented in the Echo API is using a different SequenceCommand `Alexa.Sound`. This can be verified when creating a Routine in the Alexa App by selecting *Sounds* - these are the sounds available to the script.

An example would be:
`alexa_remote_control.sh -d MyEcho -e sound:'amzn_sfx_doorbell_chime_01'`
(There is no multi-room support for this either!!!)
