### ISSUE TITLE
Way to "Drop In"  or call from device to device

### ISSUE THREAD

**Issue by Grynr38** [thorsten-gehrig/alexa-remote-control#91]
Would there be a way to programatically drop in between 2 devices with, saying a new "-c" ("Calling") parameter.
ie:
alexa_remote_control.sh -d deviceReceiving -c deviceCalling

And drop in (or call) would take place between deviceCalling and deviceReceiving.

Thanks a lot.

**Comment by adn77** [comment]
Sorry, this won't be possible any time soon. While there are some communication capabilities in the mobile app, there is no way that this can be achieved from there. Thus no way to reverse engineer.

Also I seem to recall that the communication part of Aöexa uses yet another authentication scheme...
