### ISSUE TITLE
Audible

### ISSUE THREAD

**Issue by Lyr3x** [thorsten-gehrig/alexa-remote-control#92]
Is there any chance to use the script to start audible playback?

Using the script for a whole bunch of other things, but could not manage tostart audible playback. Its not possible to include audible in alexa routines yet!

**Comment by JosXa** [comment]
`alexa_remote_control.sh -e textcommand:"play audible"` will continue your most recent audiobook, and here are the other things you can say: https://help.audible.co.uk/s/article/voice-commands-for-listening-on-alexa-devices

**Comment by 25Moritz** [comment]
A few code snippets i've implemented quick&dirty locally
Maybe this helps to implement audible.

You could register for audible with you amazon Account and use a free audiobook to develope further

####################

elif [ -n "$AUDIBLE" ] ; then
        set_var
        list_audible_books
elif [ -n "$AUDIBLEPLAY" ] ; then
        set_var
        play_audible

####################

list_audible_books()
{
# list available audiobooks (Name and asin)
TOTAL=0
FILE=${TMP}/.alexa.audible.list
${CURL} ${OPTS} -s -b ${COOKIE} -A "${BROWSER}" -H "DNT: 1" -H "Connection: keep-alive" -L\
 -H "Content-Type: application/json; charset=UTF-8" -H "Referer: https://alexa.${AMAZON}/spa/index.html" -H "Origin: https://alexa.${AMAZON}"\
 -H "csrf: $(awk "\$0 ~/.${AMAZON}.*csrf[ \\s\\t]+/ {print \$7}" ${COOKIE})" -X GET \
 "https://${ALEXA}/api/audible/audible-books?deviceSerialNumber=${DEVICESERIALNUMBER}&deviceType=${DEVICETYPE}&mediaOwnerCustomerId=${MEDIAOWNERCUSTOMERID}" > ${FILE}.tmp
TOTAL=`jq '.audibleBookList | .[].title' /tmp/.alexa.audible.list.tmp | wc -l`

echo "trackCount:"${TOTAL}""
jq '.audibleBookList | .[] | .title,.asin' /tmp/.alexa.audible.list.tmp | tee /tmp/.alexa audible.list_summary.tmp

}


####################

play_audible()
{
# start audio book by asin
# this continues the audiobook, or starts it from beginnen if its finished
${CURL} ${OPTS} -s -b ${COOKIE} -A "${BROWSER}" -H "DNT: 1" -H "Connection: keep-alive" -L\
 -H "Content-Type: application/json; charset=UTF-8" -H "Referer: https://alexa.${AMAZON}/spa/index.html" -H "Origin: https://alexa.${AMAZON}"\
 -H "csrf: $(awk "\$0 ~/.${AMAZON}.*csrf[ \\s\\t]+/ {print \$7}" ${COOKIE})" -X POST -d "{\"deviceType\":\"${DEVICETYPE}\",\"deviceSerialNumber\":\"${DEVICESERIALNUMBER}\",\"mediaOwnerCustomerId\":\"${MEDIAOWNERCUSTOMERID}\",\"asin\":\"${ASIN}\"}" \
 "https://${ALEXA}/api/audible/queue-and-play?"

}

**Comment by adn77** [comment]
Would you be willing to open a PR with your code?
I can't test as I don't own any Audible content...
