### ISSUE TITLE
-e sound not working

### ISSUE THREAD

**Issue by Grynr38** [thorsten-gehrig/alexa-remote-control#94]
Hi Alex,
I can't seem to find a way to make sound work... nor SSML in speak, I am working with **SET_USE_ANNOUNCEMENT_FOR_SPEAK="1".**

I've tried :

 `Alexa.sh -d DEVICE -e speak:'Trying <audio src="soundbank://soundlibrary/animals/amzn_sfx_bear_groan_roar_01"/>'`
It says the text but the audio/sound effect does not play

`Alexa.sh -d Salon -e speak:'Trying ding-dong <say-as interpret-as="interjection">Ding dong</say-as>.'`
It says the whole phrase "Trying ding-dong ding dong" but does not interpret the Ding dong as it shoud

`Alexa.sh -d DEVICE -e sound:'<audio src="soundbank://soundlibrary/animals/amzn_sfx_bear_groan_roar_01"/>'`
This simply does nothing at all.
**EDIT/UPDATE**: I've just found out that I should only use the identifier "amzn_sfx_doorbell_chime_01"
`Alexa.sh -d DEVICE -e sound:'amzn_sfx_doorbell_chime_01'`
**Works great... But only on one device, does not work on multiroom... And, as correctly stated of the info, only very few sounds work**

I am doing something wrong ? 
Thank you very very much for all your work. It is amazing !

**Comment by haakonstorm** [comment]
I'm working on the same as you, I'm not there yet, but a few pointers:
- There are requirements/advise from Amazon regarding the audio file and it's codec. In short, convert whatever you want to play with `ffmpeg -i <input-file> -ac 2 -codec:a libmp3lame -b:a 48k -ar 24000 <output-file.mp3>` and you are good to go.
- Your URL `soundbank://soundlibrary/animals/amzn_sfx_bear_groan_roar_01` includes a protocol `soundbank://` which is unfamilliar to me, is this a local library hosted via a local service? AFAIK, you need to host your file somewhere world readable over **https**. For example, `https://yourdomain.duckdns.org/sounds/alexasound.mp3` or `grynr38.github.io/sounds/alexasound.mp3`.

**Comment by Grynr38** [comment]
Hi Mate,
SoundBank is Amazon's own sound effects protocol :
https://developer.amazon.com/en-US/docs/alexa/custom-skills/ask-soundlibrary.html
