### ISSUE TITLE
How to refresh cookie without manually using browser

### ISSUE THREAD

**Issue by dmike3** [thorsten-gehrig/alexa-remote-control#95]
So I've manually pulled the cookie from my browser and put it into .alexa.cookie. This works, and stuff works for a couple weeks. However, just today it stopped working. I'm thinking the cookie expired.

So, I have the following setup to run 3 times a week. alexa_remote_control.sh -login. 

Will this refresh my cookie?

**Comment by mike3y** [comment]
Cookie stopped working today.

I had to go through the web browser and export again.

**Comment by adn77** [comment]
Sorry for the late answer.
Technically this script should retrieve the cookie automatically. Since Amazon nowadays almost always requires a captcha login though, this method is not reliable anymore.
Currently the only way around this is to setup MFA - there are no captcha screens so far.
