### ISSUE TITLE
Confirmed working on macOS 10.15

### ISSUE THREAD

**Issue by haakonstorm** [thorsten-gehrig/alexa-remote-control#96]
Just wanted to let you know on macOS, some of the depencies are not 100% compatible.

By replacing `sed`, `grep` etc with `gsed`, `ggrep` etc from `coreutils` (e.g. via `brew install coreutils`) you're good to go. 

I also used a more recent `curl` (`brew install curl`) but not sure if that was neccessary. 

Thanks for this, great work!

**Comment by rusyasoft** [comment]
It doesn't work for me. It keeps giving an error:

```
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
cookie does not exist. logging in ...
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
ERROR: Amazon Login was unsuccessful. Possibly you get a captcha login screen.
 Try logging in to https://alexa.amazon.com with your browser. In your browser
 make sure to have all Amazon related cookies deleted and Javascript disabled!

 (For more information have a look at /tmp/.alexa.login)

 To avoid issues with captcha, try using Multi-Factor Authentication.
 To do so, first set up Two-Step Verification on your Amazon account, then
 configure this script (or the environment) with your MFA secret.
 Support for Multi-Factor Authentication requires 'oathtool' to be installed.
```

**Comment by haakonstorm** [comment]
Try a simple search-and-replace of all invocations of `sed` in the script with the path to your compatible `sed`.
I don't right now recall exactly, but I think I searched for regex `^sed ` (meaning all lines beginning with `sed ` including the space on the end) with `$MY_SED`. Then assign MY_SED to the full path to e.g. your `GNU sed` like:
`MY_SED="/usr/local/bin/gsed"`

Then do the same with at least also replacing: 

- `grep` with `$MY_GREP`
- (assign somewhere on the top of the script `MY_GREP="/usr/local/bin/ggrep`)
- `curl` with `$MY_CURL` 
-  (assign somewhere on the top of the script `MY_CURL="/usr/local/bin/curl`)

If you still have problems, please send us the output of the following command:

```
uname -a; for tool in sed gsed grep ggrep curl; do printf '\n\n\n  *** %s *** \n\n' $tool; which -a $tool; command $tool --version; done
```

**Comment by haakonstorm** [comment]
A shortcut to find out which `sed` you have is to use the fact that the macOS bundled `sed` binary doesn't have the capacity to return its version number. That is, if you run the command `sed --version` or `sed -v` or anything, it will interpret that as options regarding the stream input and thus dump an error.

Do the same with a compatible `sed` like `gsed` via `homebrew` on macOS, you will get a proper version returned.
